var guide = {
  "title": "Bem-vindo, Caloiro!",
  "tags": [
    "Uma nova etapa...",
    "Sobre a Faculdade...",
    "Sobre o Curso...",
    "Sobre a Praxe do MIEEC...",
    "Sobre o Ambiente Estudantil...",
    "Sobre a Semana do Caloiro...",
    "Considerações finais..."
  ],
  "paragraphs": [
    "Ser estudante universitário é um trabalho em full-time... não remunerado. Caro Caloiro, pode esquecer tudo o que julga saber sobre faculdade. Os professores que sabem captar a atenção de um anfiteatro cheio são raros e os que vão beber copos com os alunos só existem na ficção. Assentar os pés no chão e perceber que a vida deu uma volta de 180 graus vai ser um processo único e a seu tempo. Na universidade tudo é diferente. Esta será a fase da sua vida em que sentirá o chão fugir debaixo dos pés mais vezes - e não estamos a referir-nos a noites de excessos. Como não poderiamos ser indiferentes, pois todos somos caloiros uma vez (verdade seja dita, seremos sempre caloiros de alguém), aqui deixamos um guia para o ajudar na adaptação a esta nova fase.",
    "Na FCT, o Caloiro vai encontrar um ambiente único, diferente das mais diversas universidades do nosso país. Somos a Faculdade com o melhor ambiente, o maior campus e um espírito académico elevadíssimo. Qualquer aluno desta Faculdade sente uma paixão ardente por esta e pelo seu Curso, onde quer que esteja, seja no reencontro com velhos amigos, seja nas saídas em jantares académicos, seja nos desafios, durezas e ensinamentos da Praxe ou nos seus resultados académicos, os quais engrandecem a nossa instituição. Todos encontram uma maneira de exaltar a FCT enquanto Faculdade e enquanto uma segunda casa. Em breve, poderá comprovar tudo isto por si mesmo.",
    "Bom, o Caloiro entrou no Muy Grande Curso de Engenharia Eletrotécnica e de Computadores. E agora? Agora, como não poderia deixar de ser, reina na sua vida a lei do \"Desermerda-te\"! O curso em si é possivelmente um dos mais díficeis e completos que a nossa Faculdade disponibiliza aos alunos que nela pretendem ingressar. Passamos pelas 4 Análises Matemáticas e pelas 3 Físicas, que em breve irá aprender a odeiar, e passamos por uma série de cadeiras interessantes e complexas, que nos deixam a mioleira toda queimada. Mas nada tema, caro Caloiro! O Curso não se faz sozinho! Esta será talvez a expressão mais emblemática que irá ouvir nos primeiros tempos pela FCT. Todos os veteranos se disponibilizam a ajudar qualquer Caloiro em aflição, sabendo pelo que passam e tendo a experiência para poder aconselhar e ensinar, e, de igual modo, irá ver que todos os seus colegas, também caloiros, irão partilhar do seu sofrimento e alegria, estando presentes em todos os momentos. Por isso, caro Caloiro, nada receie, um dia acabará o Curso!",
    "Chegamos agora a um tema controverso, mas apenas para vós, caríssimo Caloiro. A Praxe em Eletro (e em geral na FCT) é inigualável no país, assim como a sua instituição o é. O ambiente que esta faculdade nos proporciona icentiva e é proprício ao crescimento pessoal, cultural e académico que se desenvolve nas Praxes. A nossa Comissão de Praxe tem sempre como principal objetivo permitir o desenvolvimento de cada um de nós nos mais diversos níveis, quer intelectuais quer em competências transversais, num ambiente de união e de paixão pelo curso que representamos. Todo o caloiro tem o direito a participar na praxe, assim como tem o direito de escolher não fazê-lo, mas quem por lá passa, gosta e fica.",
    "Agora que vai pagar os 35€ de taxa de inscrição, já se pode sentir um verdadeiro FCTense. E como FCTense irá ter mais do que oportunidades para descomprimir e relaxar do dia-a-dia de estudos e trabalhos sem fim. Existem diversos bares e cafés espalhados pelo campus (sendo a Mininova e os seus pães de alho o mais famoso café/loja de conveniência), espaços verdes, locais de prática de desporto, um convívio renovado com matraquilhos e bilhar. Além disso, a FCT também é conhecida pelas suas festas! Desde a Semana do Caloiro às Festas do Olimpo, irás viver algumas das melhores noites da tua vida, neste mesmo campus, para mais tarde lembrar, ou não, se é que nos entendem.",
    "Eis que tem a inscrição feita, caro Caloiro, e conheceu alguns dos teus Veteranos e alguns dos teus colegas, também Caloiros. Agora, terá de esperar quase uma semana até à verdadeira ação começar, a afamada Semana do Caloiro. Esta começa com o monumental Desfile do Caloiro, que tem início no nosso campus e término no Parque da Paz, Almada, onde demonstrarás todo o amor recentemente adquirido pelo curso. Durante essa semana, esperam-lhe algumas atividades da AE, desde torneios desportivos a uma espécie de peddy-paper pelo campus (Odisseia), assim como um Festival Universitário no nosso FCTódromo, com o recorrente e inigualavél Quim Barreiros a atuar, entre muitos outros. Este ano, uma pequena mudança, para tristeza de muitos. Terá aulas nessa semana, pobre Caloiro, com cortesia da Direção da nossa Faculdade, que de vez em quando gosta de mudar as coisas... e nem sempre para melhor.",
    "Com pensamentos mais alegres, aproveite, Caloiro! Este será o melhor ano da sua vida académica, em que nada terá de fazer além das suas cadeiras e não terá responsabilidades nem preocupações ou compromissos. Levará este ano no seu coração para sempre, confie no que vos dizemos. A si, Caloiro, ao nosso Curso e à nossa Faculdade, as mais calorosas Saudações Académicas! P'la CoPe do MIEEC."
  ]
};